/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/products/": {
    get: operations["v1_products_list"];
  };
  "/api/v1/products/{slug}/": {
    get: operations["v1_products_retrieve"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ProductDetail: {
      slug: string;
      title: string;
      subtitle?: string;
      lead?: string;
      overview?: string;
      /** Format: uri */
      hero_image_url?: string;
      /** Format: uri */
      logo_url?: string;
      cta_title?: string;
      cta_body?: string;
      cta_button_label?: string;
      /** Format: uri */
      cta_button_url?: string;
      partners_body?: string;
      features: readonly components["schemas"]["ProductFeature"][];
      specs: readonly components["schemas"]["ProductSpec"][];
      sections: readonly components["schemas"]["ProductSection"][];
      gallery: readonly components["schemas"]["ProductGallery"][];
      downloads: readonly components["schemas"]["ProductDownload"][];
      related: readonly components["schemas"]["RelatedProduct"][];
    };
    ProductDownload: {
      title: string;
      /** Format: uri */
      file_url: string;
      order?: number;
    };
    ProductFeature: {
      title: string;
      body?: string;
      /** Format: uri */
      icon_url?: string;
      order?: number;
    };
    ProductGallery: {
      /** Format: uri */
      image_url: string;
      caption?: string;
      order?: number;
    };
    ProductList: {
      slug: string;
      title: string;
      subtitle?: string;
      /** Format: uri */
      hero_image_url?: string;
    };
    ProductSection: {
      title: string;
      body?: string;
      /** Format: uri */
      image_url?: string;
      order?: number;
    };
    ProductSpec: {
      group?: string;
      label: string;
      value: string;
      order?: number;
    };
    RelatedProduct: {
      title: string;
      subtitle?: string;
      /** Format: uri */
      link_url?: string;
      order?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  v1_products_list: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ProductList"][];
        };
      };
    };
  };
  v1_products_retrieve: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ProductDetail"];
        };
      };
    };
  };
}
